### PR TITLE
RUMM-3348: Allow re-export of the SDK modules

### PR DESCRIPTION
**Pull request by 0xnm**
### What does this PR do?

This change does the following:

* Allows re-export of SDK modules (by using `api` dependency)
* Renames `dd-sdk-android` module to `dd-sdk-android-core`

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

**Review by mariusc83 — APPROVED** [review]
LGTM

**Comment by hestonhoffman** [comment]
The docs team needs to do a little testing to see if we need to adjust our single-sourcing for this change. cc @rtrieu

**Comment by rtrieu** [comment]
Hi @0xnm, will we need to reroute any links in our docs from the `dd-sdk-android` repo to the `dd-sdk-android-core` repo now? For example, we currently link to the `dd-sdk-android` repo here: https://docs.datadoghq.com/real_user_monitoring/android/?tab=kotlin#declare-the-sdk-as-a-dependency

**Comment by 0xnm** [comment]
@rtrieu No, not yet. This is a PR for the SDK v2 branch, all the docs updates for the changes related to the SDK v2 will be done later.

**Review by rtrieu — APPROVED** [review]
LGTM

**Review by jonathanmos — APPROVED** [review]
LGTM

**Review by xgouchet — APPROVED** [review]

**Pull request merged**
