### PR TITLE
RUM-5873: Reactivate Session Replay instrumented test for API 21

### PR DESCRIPTION
**Pull request by ambushwork**
### What does this PR do?

Reactive Session Replay instrumented test for API 21, 
Fix a drawable resolving issue due to the different behavior on lower API.

### Motivation

RUM-5873

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

**Review by 0xnm — APPROVED** [review]
lgtm, but I believe we will still have a wrong stacktrace in case if test fails on API 21, because some classes used by AssertJ don't exist there?

**Comment by ambushwork** [comment]
@0xnm I am not sure what do you mean, can you elaborate?

**Comment by 0xnm** [comment]
I mean AssertJ is using some Java 8+ classes (ex. `java.time.*`) when printing failure message which don't exist on API 21.

**Comment by 0xnm** [comment]
The only quick workaround is desugaring, but I don't think we want to enable it. So let's keep it like that.

**Pull request merged**
