### PR TITLE
Replace Mobile Vitals image, update text and links

### PR DESCRIPTION
**Pull request by rtrieu**
### What does this PR do?

Updates the Mobile Vitals screenshot and text to match the new UI.

### Motivation

[DOCS-4882](https://datadoghq.atlassian.net/browse/DOCS-4882)

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

[DOCS-4882]: https://datadoghq.atlassian.net/browse/DOCS-4882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by xgouchet — APPROVED** [review]

**Review by 0xnm — COMMENTED** [review]
lgtm, but it seems new image is missing in this PR.

**Review by drichards-87 — APPROVED** [review]

**Comment by rtrieu** [comment]
@0xnm Thanks for noticing that, Nikita. Due to the way our single-sourcing works, screenshots are in a different repo/PR: [https://github.com/DataDog/documentation/pull/17238/files](https://github.com/DataDog/documentation/pull/17238/files)

**Review by 0xnm — APPROVED** [review]

**Review by xgouchet — APPROVED** [review]

**Comment by 0xnm** [comment]
Hello @rtrieu ! It seems that this PR is stale, is it still valid?

**Comment by xgouchet** [comment]
I think this can be discarded as we're planning to remove the docs from the repo anyway

**Comment by rtrieu** [comment]
Hi @0xnm @xgouchet yes this branch is stale, and we're moving over to the docs repo anyway, so I will close it out. Thanks!

**Pull request closed without merging**
